# Servicio Orquestador
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-orquestador-deployment
  labels:
    app: servicio-orquestador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-orquestador
  template:
    metadata:
      labels:
        app: servicio-orquestador
    spec:
      containers:
      - name: servicio-orquestador-container
        image: ghcr.io/kvel12/servicio-orquesta:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-orquestador-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
  selector:
    app: servicio-orquestador
---
# Servicio A
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-a-deployment
  labels:
    app: servicio-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-a
  template:
    metadata:
      labels:
        app: servicio-a
    spec:
      containers:
      - name: servicio-a-container
        image: ghcr.io/kvel12/servicio-a:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-a-service
spec:
  type: ClusterIP
  ports:
    - port: 3001      
      targetPort: 3001
  selector:
    app: servicio-a
---
# Servicio B
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-b-deployment
  labels:
    app: servicio-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-b
  template:
    metadata:
      labels:
        app: servicio-b
    spec:
      containers:
      - name: servicio-b-container
        image: ghcr.io/kvel12/servicio-b:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-b-service
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: servicio-b
---

# Servicio C
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-c-deployment
  labels:
    app: servicio-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-c
  template:
    metadata:
      labels:
        app: servicio-c
    spec:
      containers:
      - name: servicio-c-container
        image: docker.io/yhcarlos14/servicioc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-c-service
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: servicio-c
---

# Servicio D
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-d-deployment
  labels:
    app: servicio-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-d
  template:
    metadata:
      labels:
        app: servicio-d
    spec:
      containers:
      - name: servicio-d-container
        image: ghcr.io/josemanuel2005/serviciod:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-d-service
spec:
  type: ClusterIP
  ports:
    - port: 3004
      targetPort: 3004
  selector:
    app: servicio-d
---
# Servicio E
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-e-deployment
  labels:
    app: servicio-e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-e
  template:
    metadata:
      labels:
        app: servicio-e
    spec:
      containers:
      - name: servicio-e-container
        image: ghcr.io/vanloop/servicio-e:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-e-service
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    app: servicio-e
---

# Servicio F
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-f-deployment
  labels:
    app: servicio-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-f
  template:
    metadata:
      labels:
        app: servicio-f
    spec:
      containers:
      - name: servicio-f-container
        image: ghcr.io/mmangelmm/servicio-f:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3006
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-f-service
spec:
  type: ClusterIP
  ports:
    - port: 3006
      targetPort: 3006
  selector:
    app: servicio-f
---
