apiVersion: v1
kind: Pod
metadata:
  name: servicio-d-pod
  labels:
    app: servicio-d
spec:
  containers:
    - name: servicio-d-container
      image: fredyball/servicio-d:latest
      ports:
        - containerPort: 3004

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-d-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3004
      protocol: TCP
  selector:
    app: servicio-d