apiVersion: v1
kind: Pod
metadata:
  name: servicio-c-pod
  labels:
    app: servicio-c
spec:
  containers:
    - name: servicio-c-container
      image: fredyball/servicio-c:latest
      ports:
        - containerPort: 3003

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-c-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3003
      protocol: TCP
  selector:
    app: servicio-c